### ISSUE TITLE
Build Fail under Linux

### ISSUE THREAD

**Issue by gajdot** [angular/universal#433]
I'm submitting a bug report. I just updated to the latest source code to test if I can finally build this repo, but it fails even more then before. I get error's when I try to run `npm start` command no matter what. 

Ways to reproduce: 
`git clone git@github.com:gajdot/universal.git universal` this repo is the exact copy of master branch on angular/universal
`cd universal`
`npm install`
`npm start`
If I try to start it I get the following report: 
```

> angular2-universal@0.0.1 start /home/username/programming/universal
> cd ./examples && npm run start


> examples@0.0.0 start /home/username/programming/universal/examples
> npm run build && npm run server


> examples@0.0.0 prebuild /home/username/programming/universal/examples
> rimraf dist


> examples@0.0.0 build /home/username/programming/universal/examples
> tsc || true

src/universal/falcor_todo/services/TodoStore.ts(1,26): error TS2307: Cannot find module '@angular/core'.
src/universal/todo/services/TodoStore.ts(1,26): error TS2307: Cannot find module '@angular/core'.
src/index.ts(5,12): error TS2304: Cannot find name 'process'.
src/index.ts(8,23): error TS2307: Cannot find module 'http'.
src/index.ts(9,23): error TS2307: Cannot find module 'path'.
src/index.ts(13,17): error TS2304: Cannot find name 'process'.
src/index.ts(16,22): error TS2304: Cannot find name '__dirname'.
src/index.ts(22,12): error TS2304: Cannot find name 'require'.
src/index.ts(26,3): error TS2304: Cannot find name 'module'.
src/index.ts(38,14): error TS2304: Cannot find name 'require'.
src/index.ts(41,5): error TS2304: Cannot find name 'process'.
src/index.ts(44,3): error TS2304: Cannot find name 'module'.
src/index.ts(73,18): error TS2304: Cannot find name 'Buffer'.
src/server/express/api.ts(1,12): error TS2304: Cannot find name 'require'.
src/server/express/api.ts(2,16): error TS2304: Cannot find name 'require'.
src/server/express/api.ts(12,1): error TS2304: Cannot find name 'module'.
src/server/express/graph_api.ts(1,12): error TS2304: Cannot find name 'require'.
src/server/express/graph_api.ts(2,21): error TS2304: Cannot find name 'require'.
src/server/express/graph_api.ts(3,16): error TS2304: Cannot find name 'require'.
src/server/express/graph_api.ts(4,20): error TS2304: Cannot find name 'require'.
src/server/express/graph_api.ts(14,1): error TS2304: Cannot find name 'module'.
src/server/express/routes.ts(1,19): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(2,26): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(3,16): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(5,15): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(6,15): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(7,17): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(8,15): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(9,16): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(10,22): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(12,39): error TS2307: Cannot find module '@angular/core'.
src/server/express/routes.ts(13,20): error TS2307: Cannot find module '@angular/http'.
src/server/express/routes.ts(14,54): error TS2307: Cannot find module '@angular/common'.
src/server/express/routes.ts(28,8): error TS2307: Cannot find module 'angular2-universal'.
src/server/express/routes.ts(78,1): error TS2304: Cannot find name 'module'.
src/server/express/routes.ts(85,46): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(144,46): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(180,48): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(222,48): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(251,50): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(291,28): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(324,44): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/server.ts(1,15): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(2,19): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(3,14): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(4,12): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(6,1): error TS2304: Cannot find name 'module'.
src/server/express/server.ts(8,25): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(16,16): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(17,13): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(18,18): error TS2304: Cannot find name 'require'.
src/server/hapi/api.ts(1,12): error TS2304: Cannot find name 'require'.
src/server/hapi/api.ts(18,1): error TS2304: Cannot find name 'module'.
src/server/hapi/graph_api.ts(2,1): error TS2304: Cannot find name 'module'.
src/server/hapi/routes.ts(9,1): error TS2304: Cannot find name 'module'.
src/server/hapi/routes.ts(13,17): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(14,17): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(15,19): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(17,35): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(18,43): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(28,7): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(48,26): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/hapi/routes.ts(93,28): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/hapi/routes.ts(127,28): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/hapi/routes.ts(152,28): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/hapi/server.ts(1,19): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(2,14): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(3,12): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(4,14): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(5,16): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(6,15): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(8,1): error TS2304: Cannot find name 'module'.
src/server/hapi/server.ts(10,22): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(28,19): error TS2304: Cannot find name '__dirname'.
src/server/hapi/server.ts(34,16): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(37,13): error TS2304: Cannot find name 'require'.
src/universal/falcor_todo/app.ts(1,44): error TS2307: Cannot find module '@angular/core'.
src/universal/falcor_todo/app.ts(3,33): error TS2307: Cannot find module '@angular/router-deprecated'.
src/universal/falcor_todo/app.ts(5,20): error TS2307: Cannot find module '@angular/http'.
src/universal/falcor_todo/client.ts(1,23): error TS2307: Cannot find module '@angular/core'.
src/universal/falcor_todo/client.ts(3,25): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
src/universal/falcor_todo/client.ts(6,32): error TS2307: Cannot find module '@angular/router-deprecated'.
src/universal/falcor_todo/client.ts(8,30): error TS2307: Cannot find module '@angular/http'.
src/universal/html/app.ts(1,58): error TS2307: Cannot find module '@angular/core'.
src/universal/html/app.ts(2,46): error TS2307: Cannot find module '@angular/router-deprecated'.
src/universal/html/app.ts(3,20): error TS2307: Cannot find module '@angular/http'.
src/universal/html/browser.ts(2,26): error TS2307: Cannot find module '@angular/core'.
src/universal/html/browser.ts(5,69): error TS2307: Cannot find module '@angular/common'.
src/universal/html/browser.ts(6,25): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
src/universal/html/browser.ts(7,30): error TS2307: Cannot find module '@angular/http'.
src/universal/html/browser.ts(8,32): error TS2307: Cannot find module '@angular/router-deprecated'.
src/universal/html/html.ts(1,44): error TS2307: Cannot find module '@angular/core'.
src/universal/html/html.ts(2,27): error TS2307: Cannot find module '@angular/router-deprecated'.
src/universal/template_url/app.ts(1,25): error TS2307: Cannot find module '@angular/core'.
src/universal/template_url/browser.ts(2,26): error TS2307: Cannot find module '@angular/core'.
src/universal/template_url/browser.ts(5,25): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
src/universal/test_jsonp/app.ts(1,25): error TS2307: Cannot find module '@angular/core'.
src/universal/test_jsonp/app.ts(2,21): error TS2307: Cannot find module '@angular/http'.
src/universal/test_jsonp/app.ts(3,26): error TS2307: Cannot find module 'rxjs/Observable'.
src/universal/test_jsonp/browser.ts(2,72): error TS2307: Cannot find module '@angular/core'.
src/universal/test_jsonp/browser.ts(5,25): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
src/universal/test_jsonp/browser.ts(6,47): error TS2307: Cannot find module '@angular/http'.
src/universal/test_page/app.ts(1,25): error TS2307: Cannot find module '@angular/core'.
src/universal/test_page/app.ts(2,20): error TS2307: Cannot find module '@angular/http'.
src/universal/test_page/app.ts(3,26): error TS2307: Cannot find module 'rxjs/Observable'.
src/universal/test_page/browser.ts(2,72): error TS2307: Cannot find module '@angular/core'.
src/universal/test_page/browser.ts(5,25): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
src/universal/test_page/browser.ts(6,30): error TS2307: Cannot find module '@angular/http'.
src/universal/test_page/browser.ts(31,10): error TS2304: Cannot find name 'Promise'.
src/universal/test_router/app.ts(1,25): error TS2307: Cannot find module '@angular/core'.
src/universal/test_router/app.ts(2,46): error TS2307: Cannot find module '@angular/router-deprecated'.
src/universal/test_router/browser.ts(1,25): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
src/universal/test_router/browser.ts(2,32): error TS2307: Cannot find module '@angular/router-deprecated'.
src/universal/todo/app.ts(1,44): error TS2307: Cannot find module '@angular/core'.
src/universal/todo/app.ts(3,33): error TS2307: Cannot find module '@angular/router-deprecated'.
src/universal/todo/app.ts(5,20): error TS2307: Cannot find module '@angular/http'.
src/universal/todo/browser.ts(1,23): error TS2307: Cannot find module '@angular/core'.
src/universal/todo/browser.ts(3,25): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
src/universal/todo/browser.ts(6,32): error TS2307: Cannot find module '@angular/router-deprecated'.
src/universal/todo/browser.ts(8,30): error TS2307: Cannot find module '@angular/http'.

> examples@0.0.0 server /home/username/programming/universal/examples
> node dist/index.js
```
Which I figured it out, it must be not installing the npm in the example folder, so I did it my self:
`cd examples`
`npm install`
`cd ..`
`npm start`

If I did this, the packages are correctly installed, but I still can't run the repo, I get the following error:

```

> angular2-universal@0.0.1 start /home/username/programming/universal
> cd ./examples && npm run start


> examples@0.0.0 start /home/username/programming/universal/examples
> npm run build && npm run server


> examples@0.0.0 prebuild /home/username/programming/universal/examples
> rimraf dist


> examples@0.0.0 build /home/username/programming/universal/examples
> tsc || true

node_modules/@angular/common/src/directives/ng_class.d.ts(72,35): error TS2304: Cannot find name 'Set'.
node_modules/@angular/common/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/common/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
node_modules/@angular/common/src/facade/lang.d.ts(70,59): error TS2304: Cannot find name 'Map'.
node_modules/@angular/common/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(11,50): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/forms/directives/select_control_value_accessor.d.ts(18,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/common/src/pipes/async_pipe.d.ts(29,29): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/pipes/async_pipe.d.ts(35,38): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/pipes/async_pipe.d.ts(37,39): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/common/src/pipes/async_pipe.d.ts(39,44): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(39,88): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(99,42): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(174,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(105,123): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(105,165): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
node_modules/@angular/core/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
node_modules/@angular/core/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/lang.d.ts(70,59): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(11,50): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/component_resolver.d.ts(8,53): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/component_resolver.d.ts(12,44): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(62,148): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(103,144): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(108,139): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(109,135): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/reflection/reflector.d.ts(28,22): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/reflection/reflector.d.ts(30,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/reflection/reflector.d.ts(32,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/reflection/reflector.d.ts(34,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/reflection/reflector.d.ts(36,16): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/testability/testability.d.ts(40,20): error TS2304: Cannot find name 'Map'.
node_modules/@angular/http/src/headers.d.ts(29,18): error TS2304: Cannot find name 'Map'.
node_modules/@angular/http/src/headers.d.ts(45,59): error TS2304: Cannot find name 'Map'.
node_modules/@angular/http/src/url_search_params.d.ts(11,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/platform-browser-dynamic/platform_browser_dynamic.d.ts(75,90): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/directives/router_outlet.d.ts(27,54): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/directives/router_outlet.d.ts(33,51): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/directives/router_outlet.d.ts(38,56): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/directives/router_outlet.d.ts(47,65): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/directives/router_outlet.d.ts(58,60): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/router-deprecated/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
node_modules/@angular/router-deprecated/src/facade/lang.d.ts(70,59): error TS2304: Cannot find name 'Map'.
node_modules/@angular/router-deprecated/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/promise.d.ts(11,50): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/instruction.d.ts(125,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/instruction.d.ts(161,25): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/instruction.d.ts(179,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/instruction.d.ts(182,25): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/interfaces.d.ts(21,107): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/interfaces.d.ts(39,104): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/interfaces.d.ts(57,109): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/interfaces.d.ts(80,109): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/interfaces.d.ts(102,114): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/lifecycle/lifecycle_annotations.d.ts(29,100): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/route_config/route_config_impl.d.ts(105,19): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/route_definition.d.ts(20,20): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/route_definition.d.ts(35,20): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/route_registry.d.ts(52,66): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(56,50): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(68,46): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(86,45): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(99,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(107,64): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(112,85): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(114,51): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(116,72): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(122,48): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(128,70): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(140,43): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(144,29): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(150,19): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/router-deprecated/src/router.d.ts(162,70): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/PromiseObservable.d.ts(22,31): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/PromiseObservable.d.ts(23,26): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/operator/toPromise.d.ts(7,59): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/operator/toPromise.d.ts(7,69): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/operator/toPromise.d.ts(9,9): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/operator/toPromise.d.ts(10,26): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/operator/toPromise.d.ts(10,36): error TS2304: Cannot find name 'Promise'.
src/index.ts(5,12): error TS2304: Cannot find name 'process'.
src/index.ts(8,23): error TS2307: Cannot find module 'http'.
src/index.ts(9,23): error TS2307: Cannot find module 'path'.
src/index.ts(13,17): error TS2304: Cannot find name 'process'.
src/index.ts(16,22): error TS2304: Cannot find name '__dirname'.
src/index.ts(22,12): error TS2304: Cannot find name 'require'.
src/index.ts(26,3): error TS2304: Cannot find name 'module'.
src/index.ts(38,14): error TS2304: Cannot find name 'require'.
src/index.ts(41,5): error TS2304: Cannot find name 'process'.
src/index.ts(44,3): error TS2304: Cannot find name 'module'.
src/index.ts(73,18): error TS2304: Cannot find name 'Buffer'.
src/server/express/api.ts(1,12): error TS2304: Cannot find name 'require'.
src/server/express/api.ts(2,16): error TS2304: Cannot find name 'require'.
src/server/express/api.ts(12,1): error TS2304: Cannot find name 'module'.
src/server/express/graph_api.ts(1,12): error TS2304: Cannot find name 'require'.
src/server/express/graph_api.ts(2,21): error TS2304: Cannot find name 'require'.
src/server/express/graph_api.ts(3,16): error TS2304: Cannot find name 'require'.
src/server/express/graph_api.ts(4,20): error TS2304: Cannot find name 'require'.
src/server/express/graph_api.ts(14,1): error TS2304: Cannot find name 'module'.
src/server/express/routes.ts(1,19): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(2,26): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(3,16): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(5,15): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(6,15): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(7,17): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(8,15): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(9,16): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(10,22): error TS2304: Cannot find name 'require'.
src/server/express/routes.ts(28,8): error TS2307: Cannot find module 'angular2-universal'.
src/server/express/routes.ts(78,1): error TS2304: Cannot find name 'module'.
src/server/express/routes.ts(85,46): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(144,46): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(180,48): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(222,48): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(251,50): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(291,28): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/routes.ts(324,44): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/express/server.ts(1,15): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(2,19): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(3,14): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(4,12): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(6,1): error TS2304: Cannot find name 'module'.
src/server/express/server.ts(8,25): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(16,16): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(17,13): error TS2304: Cannot find name 'require'.
src/server/express/server.ts(18,18): error TS2304: Cannot find name 'require'.
src/server/hapi/api.ts(1,12): error TS2304: Cannot find name 'require'.
src/server/hapi/api.ts(18,1): error TS2304: Cannot find name 'module'.
src/server/hapi/graph_api.ts(2,1): error TS2304: Cannot find name 'module'.
src/server/hapi/routes.ts(9,1): error TS2304: Cannot find name 'module'.
src/server/hapi/routes.ts(13,17): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(14,17): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(15,19): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(17,35): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(18,43): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(28,7): error TS2304: Cannot find name 'require'.
src/server/hapi/routes.ts(48,26): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/hapi/routes.ts(93,28): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/hapi/routes.ts(127,28): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/hapi/routes.ts(152,28): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
src/server/hapi/server.ts(1,19): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(2,14): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(3,12): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(4,14): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(5,16): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(6,15): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(8,1): error TS2304: Cannot find name 'module'.
src/server/hapi/server.ts(10,22): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(28,19): error TS2304: Cannot find name '__dirname'.
src/server/hapi/server.ts(34,16): error TS2304: Cannot find name 'require'.
src/server/hapi/server.ts(37,13): error TS2304: Cannot find name 'require'.
src/universal/test_page/browser.ts(31,10): error TS2304: Cannot find name 'Promise'.

> examples@0.0.0 server /home/username/programming/universal/examples
> node dist/index.js

```
At this point I have no clue what's going wrong, I'm leaning towards that this is a bug. 

Current system:
`node -v` v6.2.1
`npm -v` 3.9.3
`tsc -v` 1.8.10
`lsb_release -irc`
Distributor ID: Ubuntu
Release: 14.04
Codename: trusty

It's running under a VM.

**Comment by MarkPieszak** [comment]
Thanks for posting this. I've fixed these errors actually and just need to check everything in. These are the same issues causing Windows to completely fail as well. Linked #402 #430 #369

**Comment by MarkPieszak** [comment]
This should be all set now w/ #434, everything finishes installing & `npm start` works in Windows, can you get latest and check if it finishes `npm install && npm start` @gajdot

**Comment by gajdot** [comment]
On Windows it seems to run fine. I was able to install it and run the application and the examples show up. 

On Linux I'm still waiting for it to install. One strange thing in Linux is that if I just run `npm install` it won't install by far everything. If I run `npm run install:all` then it takes just as long ( at least when it won't hang ) as on Windows, but for some reason time to time, don't know why it's hanging on `fetchMetadata - network` for a really really long time... 

What should I do when that happen? Go grab a pizza or just restart the npm install procedure?

**Comment by gajdot** [comment]
On Windows it seems to run fine. I was able to install it and run the application and the examples show up. 

On Linux I'm still waiting for it to install. One strange thing in Linux is that if I just run `npm install` it won't install by far everything. If I run `npm run install:all` then it takes just as long ( at least when it won't hang ) as on Windows, but for some reason time to time, don't know why it's hanging on `fetchMetadata - network` for a really really long time... 

What should I do when that happen? Go grab a pizza or just restart the npm install procedure?

**Comment by gajdot** [comment]
Another 20 minutes passed and it's still hanged on a new `fetchMetadata - network`... Any idea why it's hanging so much time on fetching metadata?

**Comment by gajdot** [comment]
@MarkPieszak  the first time I get a really big hangup is after this line:

```
npm info using npm@3.9.5
npm info using node@v6.2.1
npm info attempt registry request try #1 at 10:48:12 AM
npm http request GET https://registry.npmjs.org/@angular%2fcommon
npm info attempt registry request try #1 at 10:48:12 AM
npm http request GET https://registry.npmjs.org/@angular%2fcompiler
npm info attempt registry request try #1 at 10:48:12 AM
npm http request GET https://registry.npmjs.org/@angular%2fcore
npm info attempt registry request try #1 at 10:48:12 AM
npm http request GET https://registry.npmjs.org/@angular%2fhttp
npm info attempt registry request try #1 at 10:48:12 AM
npm http request GET https://registry.npmjs.org/@angular%2fplatform-browser
npm info attempt registry request try #1 at 10:48:12 AM
npm http request GET https://registry.npmjs.org/@angular%2fplatform-browser-dynamic
npm info attempt registry request try #1 at 10:48:12 AM
npm http request GET https://registry.npmjs.org/@angular%2fplatform-server
npm info attempt registry request try #1 at 10:48:12 AM
npm http request GET https://registry.npmjs.org/@angular%2frouter-deprecated
npm info attempt registry request try #1 at 10:48:12 AM
npm http request GET https://registry.npmjs.org/rxjs
npm info lifecycle angular2-universal@0.102.1~prepublish: angular2-universal@0.102.1
npm info lifecycle angular2-universal@0.102.1~prepublish: ignored because ignore-scripts is set to true angular2-universal@0.102.1
npm info lifecycle preboot@3.0.0~prepublish: preboot@3.0.0
npm info lifecycle preboot@3.0.0~prepublish: ignored because ignore-scripts is set to true preboot@3.0.0
npm http 304 https://registry.npmjs.org/rxjs
npm http 304 https://registry.npmjs.org/@angular%2fcompiler
npm http 304 https://registry.npmjs.org/@angular%2fplatform-browser
npm http 304 https://registry.npmjs.org/@angular%2fcommon
npm http 304 https://registry.npmjs.org/@angular%2frouter-deprecated
npm http 304 https://registry.npmjs.org/@angular%2fhttp
npm http 304 https://registry.npmjs.org/@angular%2fcore
npm http 304 https://registry.npmjs.org/@angular%2fplatform-server
```
Doesn't really seem to tell me much, maybe you have better idea?

**Comment by MarkPieszak** [comment]
I don't have a Linux machine otherwise I'd give a go, I wonder if it's because it's a VM maybe?

Those lines should be quick, it's just getting Angular core stuff from your npm cache (304 code). Bizarre...

**Comment by gajdot** [comment]
Well somebody with a full-blown real Linux system should test it, on windows it's working :) Unfortunately besides VM-s I don't have any Linux installed system at my disposal, only my raspberry 3, but I wouldn't like to test the build time for such a big package xD

**Comment by MarkPieszak** [comment]
Forgot about this one, the build will work now since it has been totally revamped.

    npm install
    gulp // creates all the dist folders for each module

Should be all set now.
